#!/bin/bash

# Alex Htut
# CSE_374 | HW_2
# Problem_4
# 04/17/2019

if [ $# -lt 2 ]
then
  echo "$0 takes at least two args" 1>&2
  exit 1
fi

appendFile="$1"
shift

total="$(wc -w "$@")"

date >> $appendFile

echo "${total}" >> $appendFile

if [ $# -eq 1 ]
then
  wordCount="$(wc -w < "$1")"
  echo "$wordCount total" >> $appendFile
fi

exit 0