#!/bin/bash

# Alex Htut
# CSE_374 | HW_2
# Problem_3
# 04/17/2019

if [ $# -lt 2 ]
then
  echo "Error: $0 takes at least two arguments" 1>&2
  exit 1
fi

if [[ -f "$1" ]]
then
  echo "Error: first file exist" 1>&2
  exit 1
fi

errorFile="$1"
shift

cat "$@" 2> $errorFile
exit 0

