Script started on Mon 01 Apr 2019 09:43:56 PM PDT
]0;htutk@klaatu:~[?1034h[htutk@klaatu ~]$ whoami
htutk
]0;htutk@klaatu:~[htutk@klaatu ~]$ echo $SHELL
/bin/bash
]0;htutk@klaatu:~[htutk@klaatu ~]$ pwd
/homes/htutk
]0;htutk@klaatu:~[htutk@klaatu ~]$ uname a[K-a
Linux klaatu.cs.washington.edu 4.9.84-1.el7.retpoline.x86_64 #1 SMP Sun Feb 25 15:56:57 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
]0;htutk@klaatu:~[htutk@klaatu ~]$ gcc --version -std=c11
gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

]0;htutk@klaatu:~[htutk@klaatu ~]$ exit
exit

Script done on Mon 01 Apr 2019 09:44:12 PM PDT
