#!/bin/bash

# Alex Htut
# CSE_374 | HW_2
# Problem_3
# 04/17/2019

# if less than 2 args is given,
# print error message and 
# exit with error code
if [ $# -lt 2 ]
then
  echo "Error: $0 takes at least two arguments" 1>&2
  exit 1
fi

# if the first file exists,
# print error message and
# exit with error code
if [[ -e "$1" ]]
then
  echo "Error: first file exist" 1>&2
  exit 1
fi

# the first file is where
# we print errors
errorFile="$1"
shift

# redirect if the rest of 
# the files is a dir
# or does not exist
cat "$@" 2> $errorFile
exit 0

